version: '3.3'
services:
  pg-adminer:
    image: adminer
    restart: always
    ports:
    - 8088:8080
  pg-12.0:
    image: postgres:12.0
    restart: always
    ports:
    - 5432:5432
    volumes:
    - $HOME/docker_data/volumes/postgresql/:/var/lib/postgresql/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres