version: '3.3'
services:
  pg-adminer:
    container_name: pg-adminer
    image: adminer
    restart: always
    ports:
    - 8088:8080
  pg-12.0:
    container_name: pg-12.0
    image: postgres:12.0
    restart: always
    ports:
    - 5432:5432
    volumes:
    - /var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres